### ISSUE TITLE
没有效果

### ISSUE THREAD

**Issue by 751643992** [w296488320/NullProguard#3]
我的android studio工具
![image](https://user-images.githubusercontent.com/9413175/48207291-4cab2f00-e3ab-11e8-971d-b93e70b17a86.png)

然后替换
![image](https://user-images.githubusercontent.com/9413175/48207847-7fa1f280-e3ac-11e8-8f41-842b4e9b40d8.png)
没有效果

**Comment by sudami** [comment]
我这儿替换后也无任何效果，雪论坛帖子里没人反馈，还以为就我一人呢 = =、

**Comment by w296488320** [comment]
在这 我具体说明一下 没有效果的 原因 你电脑 之前肯定 装过 as  所以 默认 的 不是现在所使用项目里面的 这种情况 你可以 搜索 Proguard-base 目录 即可 全盘搜索 全部都替换了 就OK了

**Comment by 751643992** [comment]
另外再请教一下，我下载了原来的android studio，安装了最新的android studio 3.2.1了
![image](https://user-images.githubusercontent.com/9413175/48313299-1cef6780-e5f5-11e8-88c5-6c662979ac9c.png)
![image](https://user-images.githubusercontent.com/9413175/48313305-3d1f2680-e5f5-11e8-9bd5-876644382ff0.png)
下载已经编译好的6这个替换里面的6.0.3可以吗？

**Comment by w296488320** [comment]
可以

**Comment by sudami** [comment]
都替换了也没效果 。。
